### ISSUE TITLE
Update para C# 8

### ISSUE THREAD

**Issue by claudiospinelli93** [claudiospinelli93/CalculationEngine#2]
Atualizar o projeto BackEnd da Linguagem para C# 8.

Com isso utilizar novas funções disponíveis para melhoria e legibilidade do código. 

[Link da Documentação do C# 8](https://docs.microsoft.com/pt-br/dotnet/csharp/whats-new/csharp-8)

**Comment by Vitor-Xavier** [comment]
Atualização dos projetos Common, Implementation e Language para .NET Standard 2.1, que suporta C# 8, realizada.
