### ISSUE TITLE
Documentação FrontEnd

### ISSUE THREAD

**Issue by claudiospinelli93** [claudiospinelli93/CalculationEngine#4]
- Documentação do FrontEnd.

- Documentador Métodos internamente no código. (Algo resumido e direto)

- Documentar se possível algo interno nos Métodos. (Algo resumido e direto)

- Criar Documentação MarkDown completa _Tipo C#_ com sumario com links para cada seção de métodos, tipos, enun's e tudo que for utilizado.

**Comment by Vitor-Xavier** [comment]
Documentação inicial criada em https://github.com/claudiospinelli93/CalculationEngine/wiki
